
name: Android Release

on:
  push:
    tags:
      - 'v*'   # запуск при пуше тега, например v0.1.0+1

permissions:
  contents: write  # нужно для создания релиза и загрузки assets

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build release APK
        run: flutter build apk --release

      - name: List build files (debugging)
        run: ls -R build/app/outputs

      - name: Create GitHub Release and upload APK
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/app/outputs/flutter-apk/app-release.apk
          name: "${{ github.ref_name }}"      # заголовок релиза = имя тега
          tag_name: "${{ github.ref_name }}"  # тот же тег
          prerelease: false
          draft: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
